In [1]:
from tensorflow import keras
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False  # 마이너스 표시 해결
# 한글설정
matplotlib.rcParams['font.family'] = 'Malgun Gothic' # windows 사용자
# matplotlib.rcParams['font.family'] = 'AppleGothic Gothic' # Mac사용자
matplotlib.rcParams['font.size'] = '10' # 글자크기

In [2]:
(train_input,train_target),(test_input,test_target) = keras.datasets.fashion_mnist.load_data()
train_scaled = train_input/255.0

In [3]:
train_scaled,val_scaled,train_target,val_target = train_test_split(
    train_scaled,train_target,test_size=0.2,random_state=42
)

In [4]:
model = keras.Sequential()
model.add(keras.layers.Flatten(input_shape=(28,28)))
model.add(keras.layers.Dense(100,activation='relu')) # sigmoid
model.add(keras.layers.Dropout(0.3)) # 30%를 제외시키는 규제적용
model.add(keras.layers.Dense(10,activation='softmax'))

c:\Python312\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [5]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten (Flatten)               │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 100)            │        78,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │         1,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 79,510 (310.59 KB)

 Trainable params: 79,510 (310.59 KB)

 Non-trainable params: 0 (0.00 B)

In [6]:
# model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
# # epochs 돌때마 loss,accuracy 값을 저장
# # train_scaled,val_scaled 함께 훈련시킴.
# history = model.fit(train_scaled,train_target,epochs=20,
#                     validation_data=(val_scaled,val_target))

In [7]:
model.load_weights('model0529.weights.h5')

In [8]:
model.predict(val_scaled)

375/375 ━━━━━━━━━━━━━━━━━━━━ 0s 747us/step


array([[1.6113906e-13, 6.4996279e-17, 5.9843869e-15, ..., 6.0807587e-12,
        9.9999988e-01, 1.2311228e-17],
       [3.9062795e-11, 2.5427294e-17, 2.7491434e-12, ..., 2.9629379e-16,
        1.0000000e+00, 3.1920329e-19],
       [1.4565085e-13, 2.4007489e-13, 3.7066773e-16, ..., 9.9979550e-01,
        3.6500294e-10, 5.7836900e-07],
       ...,
       [9.9797269e-08, 1.4479037e-16, 6.6816636e-10, ..., 5.0125088e-11,
        9.9999988e-01, 5.9760122e-12],
       [1.7827723e-10, 2.3203828e-15, 6.1626672e-12, ..., 1.6473590e-13,
        1.0000000e+00, 9.0010816e-17],
       [2.7605772e-01, 1.1216815e-06, 1.0274941e-03, ..., 1.3136712e-05,
        8.1544595e-06, 2.3171471e-01]], dtype=float32)

In [10]:
val_scaled

array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.00784314, 0.        , 0.43921569, ..., 0.        ,
         0.        , 0.00392157],
        [0.00784314, 0.        , 0.08235294, ..., 0.        ,
         0.00392157, 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0. 

In [9]:
val_target

array([8, 8, 7, ..., 8, 8, 1], dtype=uint8)

In [11]:
# model_weights 읽어와서 데이터 처리
val_labels = np.argmax(model.predict(val_scaled),axis=-1)
np.mean(val_labels == val_target)  # 가장높은 값중에 정답과 일치한 것만 평균으로 적용

375/375 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step


0.88575

In [12]:
val_labels

array([8, 8, 7, ..., 8, 8, 6], dtype=int64)