## Python 복습

### Markdown 수식 작성
    - LaTEX 태그로 작성 가능
$$
    \begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    \end{pmatrix}
    +
    \begin{pmatrix}
    5 & 5 & 5 \\
    5 & 5 & 5 \\
    \end{pmatrix}
$$
$$
    \begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    \end{pmatrix}
    \times
    \begin{pmatrix}
    5 & 5 \\
    5 & 5 \\
    5 & 5 \\
    \end{pmatrix}
$$

### Numpy
    - 데이터는 행렬로 표현(영상도 포함)
    - 선형대수/통계 연산을 위한 라이브러리

    Pandas : 데이터 분석에 가장 많이 활용
    Numpy : 알고리즘 활용에 numpy가 필수적 패키지

In [1]:
# 호출
import numpy as np

#### array broadcasting
    - 차원이 다른 연산을 동일한 차원으로 자동으로 변경시켜 연산을 가능하게 해주는 것
    - 딥러닝에서 bias(편향) 계산을 할 때 주로 사용

In [4]:
# 초기 가중치 생성
ary = np.array(np.random.randn(10)) # 표준정규분포를 따르는 난수 생성 -> 초기 가중치 생성 때 사용
ary

array([ 0.12413033,  1.17906622,  0.06245949, -0.85530563, -1.50063985,
       -1.38656529, -0.16530445, -0.05275192, -0.34232263,  0.56888057])

In [5]:
# 편향값 생성
bias = np.random.rand(1)
bias

array([0.76535401])

In [7]:
ary + bias # array broadcasting

array([ 0.88948434,  1.94442023,  0.82781351, -0.08995162, -0.73528584,
       -0.62121128,  0.60004956,  0.71260209,  0.42303138,  1.33423459])

### 통계함수
    - max, min, mean, median, var, std

In [8]:
np.max(ary), np.min(ary) # min-max normalization때 사용 -> 데이터 정규화

(1.1790662176418996, -1.5006398475139033)

### Random 모듈
- seed: 랜덤 모듈의 규칙값. 난수 생성 환경 고정
- randint: 균등분포로 정수 생성
- randn: 정규분포로 난수 생성
- shuffle: 무작위 섞기
- choice: 특정확률로 데이터 뽑기

#### seed

In [9]:
seed = 603 # 머신러닝, 딥러닝에서 하이퍼파라미터로 사용

np.random.seed(seed)
r1 = np.random.rand(10)

np.random.seed(1)
r2 = np.random.rand(10)

np.random.seed(seed)
r3 = np.random.rand(10)

In [10]:
r1, r2, r3

(array([0.06450168, 0.13338277, 0.10931622, 0.97127506, 0.85101842,
        0.96534748, 0.99727133, 0.93093441, 0.48533923, 0.63427833]),
 array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
        3.96767474e-01, 5.38816734e-01]),
 array([0.06450168, 0.13338277, 0.10931622, 0.97127506, 0.85101842,
        0.96534748, 0.99727133, 0.93093441, 0.48533923, 0.63427833]))

※ 머신러닝 예시
- scaling 처리 후 return 값으로 ndarray 타입 데이터로 출력

In [2]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd

X = np.random.randint(1, 100, 10).reshape(-1, 2) # 5행 2열 데이터 생성
df = pd.DataFrame(X)

df

0   1
0  91  19
1  63  27
2  87  81
3  16  37
4  67  51

In [3]:
scaled_data = MinMaxScaler().fit_transform(df)
scaled_data, type(scaled_data)

(array([[1.        , 0.        ],
        [0.62666667, 0.12903226],
        [0.94666667, 1.        ],
        [0.        , 0.29032258],
        [0.68      , 0.51612903]]),
 numpy.ndarray)

※ 머신러닝 예시
- 초기값을 임의로 생성하여 zero 생성하여 대입할 때 다음과 같은 행렬을 작성하시오

$$
    \begin{pmatrix}
    난수 & 0 & 0 & 0 \\
    0 & 난수 & 0 & 0 \\
    0 & 0 & 난수 & 0 \\
    0 & 0 & 0 & 난수 \\
    \end{pmatrix}
$$

In [5]:
zero_ary = np.zeros((4, 4))
zero_ary

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
import numpy as np

w = np.random.randn(4)
shp = np.zeros((4, 4))

for i in range(shp.shape[0]):
    for j in range(shp.shape[1]):
        if i == j: shp[i][j] = w[i]
        
shp

array([[-1.65173587,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.81300191,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.79287987,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.88166349]])

In [7]:
import numpy as np
diag_matrix = np.diag(np.random.rand(4))

diag_matrix

array([[0.8236463 , 0.        , 0.        , 0.        ],
       [0.        , 0.96370667, 0.        , 0.        ],
       [0.        , 0.        , 0.59746668, 0.        ],
       [0.        , 0.        , 0.        , 0.38654102]])

### Function
- 반복성을 줄이고 함수로 선언한 연산을 재사용
- 객체 지향 언어의 가장 큰 장점

```python
def 함수명(파라미터):
    return 출력값
```

In [8]:
# 리턴을 선언하지 않고 사용하는 경우 -> 함수가 연산 도구로만 사용될 때
# 전역변수, 지역변수
num = 603
print(num)

def today():
    num = 604
    print(num)
    
today()   
    
print(num)

603
604
603


In [9]:
num = 603
print(num)

def today():
    global num
    
    num = 604
    print(num)
    
today()   
print("=============")
print(num)

603
604
604


#### map 함수와 pandas apply는 유사한 기능
- 순서가 있는 데이터값에 함수를 모두 적용하여 결과를 출력하는 함수

```python
map(적용할 함수, 입력할 데이터)
```

In [10]:
num_txt = "1 2 3 4 5 6"
num_int = list(map(int, num_txt.split(" ")))

num_int

[1, 2, 3, 4, 5, 6]

#### lambda 함수
- 간단한 연산을 구현하여 일시적으로 사용하는 함수

```python
lambda 리턴: 연산
```

In [12]:
seq = np.random.randint(1, 101, 10)
q = list(map(lambda x: x//3, seq))

seq, q

(array([45, 30, 21, 29, 79, 40, 43, 89, 40, 72]),
 [15, 10, 7, 9, 26, 13, 14, 29, 13, 24])