In [16]:
import numpy as np
import pandas as pd

In [1]:
from tensorflow import keras
(train_input,train_target),(test_input,test_target) = keras.datasets.fashion_mnist.load_data()

In [2]:
train_input[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  

In [3]:
# 훈련세트 - 전처리
train_scaled = train_input/255
train_scaled = train_scaled.reshape(-1,28*28)

In [6]:
# 테스트세트 - 전처리
test_scaled = test_input/255
test_scaled = test_scaled.reshape(-1,28*28)

In [4]:
import tensorflow as tf


In [8]:
# 딥러닝 - 인공신경망 모델
from sklearn.model_selection import train_test_split

# 머신러닝 - cross_validate:검증세트
# 딥러닝 - cross_validate: 사용하면 좋지만, 시간이 너무 많이 걸림. 

# 딥러닝 - 훈련세트,검증세트,테스트세트(train,val,test)

train_scaled,val_scaled,train_target,val_target = train_test_split(
    train_scaled,train_target,test_size=0.2,random_state=42
)

In [12]:
print(train_scaled.shape,train_target.shape)

(48000, 784) (48000,)


In [13]:
print(val_scaled.shape,val_target.shape)

(12000, 784) (12000,)


In [17]:
np.unique(train_target)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [21]:
# 딥러닝 훈련
# 1. dense층

# 10 : target 클래스
# activation='softmax' : 활성화함수
# input_shape : 입력된 데이터 사이즈
dense = keras.layers.Dense(10,activation='softmax',input_shape=(784,))

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [24]:
np.unique(train_target)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [25]:
# 2. 모델결정
model = keras.Sequential([dense])

# 3. 모델설정부분
# loss : 다중분류 결과값을 원핫인코딩을 사용하지 않으면 sparse_categorical_crossentropy
# loss : 다중분류 결과값을 원핫인코딩을 사용하면 categorical_crossentropy
# 이진분류 : 원핫인코딩을 사용하지 않으면 sparse_binary_crossentropy
# 이진분류 : 원핫인코딩을 사용하면 binary_crossentropy
model.compile(loss='sparse_categorical_crossentropy',metrics=['accuracy'])


In [26]:
# 4. 모델 훈련
# 반복횟수 : epochs 
# batch_size=32 디폴트
# model.fit(train_scaled,train_target,batch_size=32,epochs=5)
model.fit(train_scaled,train_target,epochs=5)

Epoch 1/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 1s 569us/step - accuracy: 0.7330 - loss: 0.7884
Epoch 2/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 1s 570us/step - accuracy: 0.8360 - loss: 0.4828
Epoch 3/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 1s 571us/step - accuracy: 0.8477 - loss: 0.4495
Epoch 4/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 1s 592us/step - accuracy: 0.8531 - loss: 0.4355
Epoch 5/5
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 1s 583us/step - accuracy: 0.8507 - loss: 0.4393


In [28]:
# 5. 모델 평가 - 손실률,정확도
model.evaluate(val_scaled,val_target)

375/375 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step - accuracy: 0.8455 - loss: 0.4421


[0.44913163781166077, 0.8458333611488342]

In [ ]:
# 머신
# 모델결정 sc = SGDC...
# 모델훈련 sc.fit()
# 모델평가 sc.score()

In [ ]:
# 층만들기 dense = keras.layers.Dense(10,activation='softmax',input_shape=(784,))
# 모델결정 model = keras.Sequential([dense])
# 모델설정 model.compile(loss='sparse_categorical_crossentropy',metrics=['accuracy'])
# 모델훈련 model.fit(train_scaled,train_target,epochs=5)
# 모델평가 model.evaluate(val_scaled,val_target)