In [54]:
# from sklearn import svm,metrics
# from sklearn.neighbors import KNeighborsClassifier # 분류
# from sklearn.neighbors import KNeighborsRegressor  # 회귀-예측
from sklearn.linear_model import LinearRegression  # 선형회귀
from sklearn.preprocessing import PolynomialFeatures # 다항특성을 만들어주는 라이브러리
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False  # 마이너스 표시 해결
# 한글설정
matplotlib.rcParams['font.family'] = 'Malgun Gothic' # windows 사용자
# matplotlib.rcParams['font.family'] = 'AppleGothic Gothic' # Mac사용자
matplotlib.rcParams['font.size'] = '10' # 글자크기

In [55]:
import pandas as pd
df = pd.read_csv('https://bit.ly/fish_csv')
df.head(3)

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961

In [56]:
# 데이터 확인 : nan, 0, 타입, 최소값, 최대값, 값이 분포, 각 특성별 데이터 최대값
# 1. 데이터전처리 - data,target 분리
fish_input = df.iloc[:,1:].to_numpy()
fish_target = df['Species'].to_numpy()

# train,test세트 분리
train_input,test_input,train_target,test_target = train_test_split(
    fish_input,fish_target
)

# 표준화 작업
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [57]:
# 2. 데이터 실습시키기
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_scaled,train_target)

LogisticRegression()

In [58]:
# 3. 데이터 예측
predict = lr.predict(test_scaled[:5])
print(predict)

['Parkki' 'Perch' 'Smelt' 'Perch' 'Bream']


In [59]:
# 4. 데이터 정답률 - train,test
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))

0.8235294117647058
0.775


In [64]:
lr.classes_

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [81]:
# 2. 데이터 실습시키기
from sklearn.linear_model import LogisticRegression
# max_iter : 반복횟수=100 기본설정
# C 규제 : 올라가면 규제가 약해지고, 낮아지면 규제가 강해짐,  선형회귀 규제 - alpha값으로 지정
lr = LogisticRegression(C=30, max_iter=1000)
lr.fit(train_scaled,train_target)

LogisticRegression(C=30, max_iter=1000)

In [82]:
# 4. 데이터 정답률 - train,test
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))

0.9411764705882353
0.85


In [83]:
lr.predict(test_scaled[:5])

array(['Parkki', 'Roach', 'Smelt', 'Perch', 'Bream'], dtype=object)

In [84]:
proba = lr.predict_proba(test_scaled[:5])
print(np.round(proba,decimals=3))

[[0.007 0.792 0.004 0.    0.154 0.    0.044]
 [0.    0.023 0.3   0.003 0.631 0.005 0.038]
 [0.    0.001 0.067 0.    0.001 0.931 0.   ]
 [0.    0.002 0.835 0.006 0.119 0.    0.037]
 [0.989 0.009 0.    0.    0.    0.    0.002]]


In [85]:
0.007+ 0.792+ 0.004+ 0.+    0.154 +0. +   0.044

1.0010000000000001

In [65]:
#### 결과값 도출 형태 분석 ####

In [66]:
predict = lr.predict(test_scaled[:5])
print(predict)

# 기울기,y절편의 값을 적용시켜서 z 점수 출력
# softMax함수를 적용해서 가장 높은 확률을 채택해서 결정함.

['Parkki' 'Perch' 'Smelt' 'Perch' 'Bream']


In [68]:
lr.classes_

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [67]:
proba = lr.predict_proba(test_scaled[:5])
np.round(proba,decimals=3)

array([[0.086, 0.318, 0.261, 0.013, 0.253, 0.018, 0.052],
       [0.015, 0.093, 0.53 , 0.026, 0.261, 0.033, 0.042],
       [0.   , 0.034, 0.151, 0.001, 0.041, 0.77 , 0.002],
       [0.024, 0.039, 0.627, 0.051, 0.196, 0.004, 0.059],
       [0.867, 0.054, 0.018, 0.007, 0.021, 0.   , 0.034]])

In [69]:
decision = lr.decision_function(test_scaled[:5])
print(np.round(decision,decimals=2))

[[ 0.08  1.38  1.18 -1.84  1.15 -1.52 -0.43]
 [-1.54  0.32  2.05 -0.95  1.35 -0.73 -0.49]
 [-4.44  0.93  2.41 -2.25  1.11  4.04 -1.79]
 [-0.82 -0.32  2.45 -0.06  1.29 -2.64  0.1 ]
 [ 4.21  1.43  0.33 -0.63  0.48 -6.78  0.96]]


In [70]:
from scipy.special import softmax

proba = softmax(decision,axis = 1)
print(np.round(proba,decimals=3))

[[0.086 0.318 0.261 0.013 0.253 0.018 0.052]
 [0.015 0.093 0.53  0.026 0.261 0.033 0.042]
 [0.    0.034 0.151 0.001 0.041 0.77  0.002]
 [0.024 0.039 0.627 0.051 0.196 0.004 0.059]
 [0.867 0.054 0.018 0.007 0.021 0.    0.034]]
